name: StaffPlus
version: plugin-version
description: The ultimate moderation plugin!
author: Shortninja
website: http://shortninja.net
main: net.shortninja.staffplus.StaffPlus
softdepend: [PacketListenerApi]